services:
  app:
    build:
      context: .
      target: dev
    ports:
      - '5000:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

  db:
    ports:
      - '5433:5432'
    env_file:
      - .env.local

  redis:
    ports:
      - '6399:6379'
    env_file:
      - .env.local
