services:
  app:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - FRA

  db:
    image: postgres:17-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - FRA

  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - FRA

  # Optional: Redis monitoring
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    networks:
      - FRA

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - '5055:80'
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - FRA

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  FRA:
    driver: bridge
